--Excersise 2 Altering Tables
Alter table ZIPCODE_INFO ADD STATE VARCHAR(2);


ALTER table INSTRUCTOR_INFO ADD STREET_ADDRESS VARCHAR(50),ZIP_CODE VARCHAR(5);


ALTER table COURSE_INFO ADD COURSE_NAME VARCHAR(50), COURSE_PREREQUISTE NUMERIC(8,0);


ALTER table STUDENT_INFO ADD STREET_ADDRESS VARCHAR(50), ZIP_CODE VARCHAR(5);

ALTER table SECTION_INFO ADD LOCATION VARCHAR(50), CAPACITY NUMERIC(3,0);


ALTER table ENROLLMENT_INFO  ADD ENROLLMENT_DATE  DATE;
